# Site settings
title: Bruno Croci's Portfolio
email: bruno@croci.me
description: > # this means to ignore newlines until "baseurl:"
  Bruno Croci's Portfolio
baseurl: # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: CrociDB
github_username:  CrociDB

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

links:
  - title: About
    url: http://crocidb.com/about/
    external: true
  - title: Blog
    url: http://crocidb.com/
    external: true
  - title: Twitter
    url: http://twiter.com/CrociDB
    external: true

collections:
  games:
    output: true
    permalink: /game/:slug/
  mobile:
    output: true
    permalink: /mobile/:slug/


